- !ruby/object:Dungeon
  :name: 深き霧の森
  :desired: 0
  :monsters:
    - 
      - :worm
      - :worm
      - :rat
      - :rat
    - 
      - :worm
      - :worm
      - :worm
      - :rat
      - :rat
      - :hawk
    - 
      - :rat
      - :rat
      - :hawk
      - :hawk
      - :boar

- !ruby/object:Dungeon
  :name: イムラヤ山道
  :desired: 10
  :monsters:
    - 
      - :warm
      - :warm
      - :rat
      - :rat
    - 
      - :warm
      - :warm
      - :warm
      - :rat
      - :rat
      - :hawk
    - 
      - :rat
      - :rat
      - :hawk
      - :hawk
      - :boar

- !ruby/object:Dungeon
  :name: サファイア海蝕洞
  :desired: 20
  :monsters:
    -
      - 
      - :warm
      - :warm
      - :rat
      - :rat
    - 
      - :warm
      - :warm
      - :warm
      - :rat
      - :rat
      - :hawk
    - 
      - :rat
      - :rat
      - :hawk
      - :hawk
      - :boar
